name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 * * * *"}]
  # (optional) Run workflow manually
  # workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS }}          
          filename: metrics.entropyhub.svg
          user: MattWillFlood
          repo: EntropyHub
          #plugin_lines: yes
          #plugin_followup: yes
          #plugin_projects: no
          # plugin_projects_repositories: lowlighter/metrics/projects/1
